apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pod-info
  name: pod-info
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-info
  template:
    metadata:
      labels:
        app: pod-info
    spec:
      imagePullSecrets:
        - name: gitlab-registry-credentials
      containers:
      - image: registry.gitlab.com/kyriakos_tsalia/pod-info-app:49-edb5c65f
        name: pod-info
        ports:
        - containerPort: 8080
        env:
        - name: TABLE_STYLE
          valueFrom:
            configMapKeyRef:
              name: pod-info-cm
              key: TABLE_STYLE
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SA
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: REQUEST_CPU
          valueFrom:
            resourceFieldRef:
              containerName: pod-info
              resource: requests.cpu
        - name: LIMIT_CPU
          valueFrom:
            resourceFieldRef:
              containerName: pod-info
              resource: limits.cpu
        - name: REQUEST_MEM
          valueFrom:
            resourceFieldRef:
              containerName: pod-info
              resource: requests.memory
        - name: LIMIT_MEM
          valueFrom:
            resourceFieldRef:
              containerName: pod-info
              resource: limits.memory